spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_sharing
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 18000

app:
  cors:
    origins: http://localhost:4200
